### ISSUE TITLE
Floating IP range end is smaller than range start

### ISSUE THREAD

**Issue by tahder** [cloudbase/v-magine#1]
I tried to assign Floating IP range start to 10.20.30.50  and then Floating IP range end 10.20.30.175 it will display "OpenStack configuration Floating IP range is smaller than range start" which I could not proceed. 

I tried to change the start range to 10.20.30.050 this will continue, but the rdo or the display something (in packstack something) that invalid IP which keeps on looping the installations and could not finish.

As per observation, it only comparing the last octet; as I can proceed if less than 17 or equal in the start range.

**Comment by alexpilotti** [comment]
Closed by: bf946548e6054ff2344d0adc43f30d35ad83f14a
