### ISSUE TITLE
V-Magine installation fails because of outdated CentOS Urls

### ISSUE THREAD

**Issue by max00346** [cloudbase/v-magine#25]
Hi there,

i tried to install V-Magine with the in installer, but it stuck on this point:

![SharedScreenshot](https://user-images.githubusercontent.com/59795180/86023155-971f6a80-ba2b-11ea-82a5-87890800d1a5.jpg)

So i think maybe the URL's of the CentOS images are not available anymore, respectively the Version is not supported anymore.

I really want to use the Installer again, so thanks for any help!

**Comment by alexpilotti** [comment]
Hi apologies for the late reply! Updated to CentOS 7.9, fixed.
